version: "3.9"

services:
  api:
    build:
      context: .
    image: maurdihen/hw26
    ports:
      - 80:80
    volumes:
      - ./default_config.py:/code/config.py
    depends_on:
      pg:
        condition: service_healthy
    platform: linux/amd64
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: hw26
      POSTGRES_PASSWORD: hw26_password
      POSTGRES_DB: hw26
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5